[app]

# (str) Title of your application
title = Spy Camera App

# (str) Package name
package.name = spycamera

# (str) Package domain (needed for android packaging)
package.domain = org.test

# (str) Source code where the main.py lives
source.dir = .

# (list) Source files to include
source.include_exts = py,png,jpg,kv,atlas

# (list) List of exclusions to skip compiling Python unit tests
source.exclude_patterns = license, test, tests, */test/*, */tests/*

# (list) Application requirements
requirements = hostpython3==3.11.0, python3==3.11.0, kivy, opencv, pyjnius

# (str) Supported orientation
orientation = portrait

# (bool) Fullscreen application mode
fullscreen = 0

# (int) Target Android API
android.api = 33

# (int) Minimum Android API required
android.minapi = 24

# (str) Android NDK version
android.ndk = 25b

# (bool) Automatically accept SDK licenses
android.accept_sdk_license = True

# (str) Target single modern architecture (prevents long dual builds and log truncation)
android.archs = arm64-v8a

# (list) Required camera permissions
android.permissions = CAMERA, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE
